
describe('Magento Software Testing', () => {

  it('Main System Test Cases', () => {

    cy.visit('/#google_vignette')
    cy.get("[href='https://magento.softwaretestingboard.com/customer/account/create/']").eq(0).click()
    cy.get("[title='First Name']").type(faker.person.firstName('male'))
    cy.get("[title='Last Name']").type(faker.person.lastName('male'))
    cy.get("[title='Email']").type(faker.internet.email())
    cy.get("[title='Password']").type('test12345$')
    cy.get("[title='Confirm Password']").type('test12345$')
    cy.get("[title='Create an Account']").click()
    cy.get('body').should('contain', 'Welcome')
    cy.get('body').should('contain', 'Thank you for registering with Main Website Store.')
    cy.get(".ui-menu-icon").eq(3).click()
    cy.get("[href='https://magento.softwaretestingboard.com/men/tops-men/jackets-men.html']").eq(1).click()
    cy.get("[alt='Lando Gym Jacket']").click()
    cy.get("[aria-label='L']").click()
    cy.get("[aria-label='Green']").click()
    cy.get("[title='Qty']").clear().type('2')
    cy.get("[title='Add to Cart']").click()
    cy.get('body').should('contain', 'You added Lando Gym Jacket to your shopping cart.')
    cy.get(".showcart").click()
    cy.get(".viewcart").click()
    cy.get("[title='Update Shopping Cart']").click()
    cy.get("[href='https://magento.softwaretestingboard.com/gear.html']").click()
    cy.get("[href='https://magento.softwaretestingboard.com/gear/watches.html']").eq(2).click()
    cy.get("[alt='Luma Analog Watch']").click({ multiple: true})
    cy.get("[title='Qty']").clear().type('2')
    cy.get("[title='Add to Cart']").click()
    cy.get('body').should('contain', 'You added Luma Analog Watch to your shopping cart.')
    cy.get(".showcart").click()
    cy.get("[title='Proceed to Checkout']").click()
    cy.get("[name='firstname']").clear().type('Test')
    cy.get("[name='lastname']").clear().type('Cases')
    cy.get("[name='company']").type(faker.company.name())
    cy.get("[name='street[0]']").type(faker.location.streetAddress())
    cy.get("[name='city']").type(faker.location.city())
    cy.get("[name='postcode']").type(faker.location.zipCode())
    cy.get("[name='country_id']").select('Canada')
    cy.get("[name='region_id']").select('Ontario')
    cy.get("[name='telephone']").type(faker.phone.number({ style: 'national' }))
    cy.get("[checked='true']").click()
    cy.get("[data-role='opc-continue']").click()
    cy.get('body').should('contain', 'Order Summary')
    cy.get('body').should('contain', 'Payment Method')
    cy.get("[title='Place Order']").click()
    cy.get('body').should('contain', 'Thank you for your purchase!')
    cy.get('body').should('contain', 'Your order number is:')
    
  })
  it('Adding and Removing Product from Cart', () => {

    cy.login()
    
    cy.get("[href='https://magento.softwaretestingboard.com/women.html']").click()
    cy.get("[href='https://magento.softwaretestingboard.com/women/tops-women/hoodies-and-sweatshirts-women.html']").eq(1).click()
    cy.get("[alt='Circe Hooded Ice Fleece']").click()
    cy.get("[aria-label='M']").click()
    cy.get("[aria-label='Purple']").click()
    cy.get("[title='Add to Cart']").click()
    cy.get('body').should('contain', 'You added Circe Hooded Ice Fleece to your shopping cart.')
    cy.get("[title='Juliana Short-Sleeve Tee']").click()
    cy.get("[aria-label='XL']").click()
    cy.get("[aria-label='Yellow']").click()
    cy.get("[title='Add to Cart']").click()
    cy.get('body').should('contain', 'You added Juliana Short-Sleeve Tee to your shopping cart.')
    cy.get(".showcart").click()
    cy.get('body').should('contain', '$110.00')
    cy.get("[title='Remove item']").eq(0).click()
    cy.get(".action-accept").click()
    cy.get('body').should('contain', '$68.00')
    cy.get("[title='Remove item']").eq(1).click()
    cy.get('body').should('contain', 'Are you sure you would like to remove this item from the shopping cart?')
    cy.get('.action-primary > span').click()
    cy.get('body').should('contain', 'ou have no items in your shopping cart.')
  });
  it.only('Search for Product Using the Search Bar', () => {
    cy.login()

    cy.get("[placeholder='Search entire store here...']").type('Impulse Duffle')
    cy.get("[title='Search']").click()
    cy.get('body').should('contain', 'Search results for:')
    
  });
})