describe('Magento Software Testing', () => {

  it('', () => {
    cy.visit('https://magento.softwaretestingboard.com/#google_vignette')
    cy.get('.authorization-link').eq(0).click()
    cy.get("[title='Email']").type('cristianoronaldo@gmail.com')
    cy.get("[title='Password']").type('test12345$')
    cy.get("[name='send']").eq(0).click()
    cy.get('body').should('contain', 'Welcome, Test Cases!')
    cy.get(".ui-menu-icon").eq(3).click()
    cy.get("[href='https://magento.softwaretestingboard.com/men/tops-men/jackets-men.html']").eq(1).click()
    cy.get("[alt='Lando Gym Jacket']").click()
    cy.get("[aria-label='L']").click()
    cy.get("[aria-label='Green']").click()
    cy.get("[title='Qty']").clear().type('2')
    cy.get("[title='Add to Cart']").click()
    cy.get('body').should('contain', 'You added Lando Gym Jacket to your shopping cart.')
    cy.get(".showcart").click()
    cy.get(".viewcart").click()
    cy.get("[title='Update Shopping Cart']").click()
    cy.get("[href='https://magento.softwaretestingboard.com/gear.html']").click()
    cy.get("[href='https://magento.softwaretestingboard.com/gear/watches.html']").eq(2).click()
    cy.get("[alt='Luma Analog Watch']").click()
    cy.get("[title='Qty']").clear().type('2')
    cy.get("[title='Add to Cart']").click()
    cy.get('body').should('contain', 'You added Luma Analog Watch to your shopping cart.')
    cy.get(".showcart").click()
    cy.get("[title='Proceed to Checkout']").click()
    cy.get("[name='firstname']").clear().type('Test')
    cy.get("[name='lastname']").clear().type('Cases')
  })
})